version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/java-benchmark
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --update curl git openssh openjdk8 nss maven && rm -rf /var/cache/apk/*
      - restore_cache:
          key: java-benchmark-{{ checksum "pom.xml" }}
      - run: mvn --fail-never dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: java-benchmark-{{ checksum "pom.xml" }}

      - run:
          name: Build Java Benchmark
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            mvn clean deploy

